#!/bin/bash
###################################
# 描述：用于使用钉钉机器人发送文本消息
# 配置：需要设置access_token
# 用法：notify_dingding "文本内容"
###################################
run_home=$(cd $(dirname $0);pwd)
run_name=$(basename $0)
run_lock_file=${run_home}/lock_${run_name}
run_date_time=$(date +'%Y-%m-%d %H:%M')
###################################
# 配置信息
access_token=xx
###################################
function send_text(){
curl 'https://oapi.dingtalk.com/robot/send?access_token=${access_token}' \
   -H 'Content-Type: application/json' \
   -d '
  {"msgtype": "text",
    "text": {
        "content": "时间：'${run_date_time}',事件：'$1'"
     }
  }'
}
send_text $1
